server:
  error:
    include-stacktrace: on_param

spring:
  data:
    web:
      pageable:
        default-page-size: 12

  data-source:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
